/*
	ODBO provider for XMLA data stores
    Copyright (C) 2014  Yalos Software Labs
	http://www.arquery.com

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

	@description
					a tabular rowset generated by a MDX query (drillthrough)
*/


#include "stdafx.h"
#include "tabular_rowset.h"
#include "data_source.h"



ATLCOLUMNINFO* tabular_row_data::GetColumnInfo(void* pThis, DBORDINAL* pcCols)
{
	return static_cast< tabular_rowset* >( pThis )->mConnectionHandler->access_tab_data().GetColumnInfo( pcCols );
}

HRESULT tabular_rowset::Execute(DBPARAMS * /*pParams*/, DBROWCOUNT* pcRowsAffected)
{
	IExtendCommand* pIExtCommand = NULL;
	HRESULT hr = m_spUnkSite->QueryInterface( __uuidof( IExtendCommand ), ( void**) &pIExtCommand );
	
	if FAILED( hr ) return hr;

	pIExtCommand->GetConnectionHandler( (void**)&mConnectionHandler );

	pIExtCommand->Release();

	const int row_count = mConnectionHandler->access_tab_data().row_count();
	const int data_size = mConnectionHandler->access_tab_data().data_size();

	if ( (NULL != pcRowsAffected) && (NULL != mConnectionHandler) )
	{
		*pcRowsAffected = row_count-1;
	}

	for ( int i = 1; i < row_count; ++i )
	{
		tabular_row_data crt(data_size);
		mConnectionHandler->access_tab_data().load_at( i, (wchar_t*)&crt );
		m_rgRowData.Add( crt );
	}



	return S_OK;
}