/*
	ODBO provider for XMLA data stores
    Copyright (C) 2014  Yalos Software Labs
	http://www.arquery.com

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

	@description
					XMLAProvider.idl : IDL source for XMLAProvider

	This file will be processed by the MIDL tool to
	produce the type library (XMLAProvider.tlb) and marshalling code.
*/

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(27958A5E-8C87-4CFA-B293-7940DE842E24),
	version(1.0),
]
library XMLAProviderLib
{

	importlib("stdole2.tlb");
	[
		uuid(9F230A70-FA10-4F1E-9CBC-A638CA5C36A9)		
	]
	coclass XMLAData
	{
		interface IUnknown;
	};
	[
		uuid(62FA394B-381B-42B2-999E-8C6AE4807639)		
	]
	coclass XMLAConnection
	{
		[default] interface IUnknown;
	};
	[
		uuid(BEA8546D-C085-4219-B88C-C875B75ABF60)		
	]
	coclass XMLAConnectionDlg
	{
		[default] interface IUnknown;
	};
	[
		uuid(CE03B050-C3C1-44A2-B1F6-1579F621C34D)		
	]
	coclass XMLAAdvancedDlg
	{
		[default] interface IUnknown;
	};
	[
		uuid(AAA5BCA5-45EA-4707-86A2-E02D72CF17AB)		
	]
	interface IGetSelf : IUnknown
	{
		HRESULT GetSelf( void** pSelf );
	};
	[
		uuid(E83F39FC-E281-460E-AF64-EA3AC885C473)		
	]
	interface IExtendCommand : IUnknown
	{
#if _WIN64
		HRESULT GetAxisRowset(IUnknown * pUnkOuter, REFIID riid, void * pParams, LONGLONG  * pcRowsAffected, IUnknown ** ppRowset);
#else
		HRESULT GetAxisRowset(IUnknown * pUnkOuter, REFIID riid, void * pParams, LONG  * pcRowsAffected, IUnknown ** ppRowset);
#endif
		HRESULT GetConnectionHandler( void** connection );
	};
};

